default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: shopping_app_development

test:
  <<: *default
  database: shopping_app_test

production:
  <<: *default
  database: shopping_app_production
  username: 
  password: 
